export {
   attachDocumentToDriverSession,
   cleanupStaleDriverSessions,
   createDoctorReport,
   DriverCommandError,
   driverCommandSets,
   getDriverSessionMetadataPath,
   getDriverSessionStatus,
   getDriverSocketPath,
   inspectApplicableTarget,
   inspectApplicableUrl,
   inspectCriterionTarget,
   inspectCriterionUrl,
   isDriverCommandSet,
   listCliCommands,
   listDriverCommands,
   listSupportedTargets,
   listWcagCriteria,
   listWcagLevels,
   openUrlInSystemAutomationBrowser,
   parseDriverCommandSet,
   renderDoctorText,
   resolveAvailableDefaultTarget,
   resolveDefaultTarget,
   resolveDocumentTarget,
   resolveDriverCommand,
   resolveTargetType,
   runAxe,
   runDriverSessionAction,
   runEphemeralDriverAction,
   searchWcagCriteria,
   showWcagCoverage,
   showWcagCriterion,
   startDriverSession,
   stopDriverSession,
   CliEnvironmentError,
   CliUsageError,
} from '@a11ied/core';

export type {
   AxeRunOptions,
   ConcreteDriverCommandSet,
   DriverCommandList,
   DriverCommandSet,
   ListDriverCommandsOptions,
   ResolveDocumentTargetInput,
   SerializableDriverCommand,
   SessionActionOptions,
   TargetType,
} from '@a11ied/core';
