export {
   attachDocumentToDriverSession,
   cleanupStaleDriverSessions,
   getDriverSessionMetadataPath,
   getDriverSessionStatus,
   getDriverSocketPath,
   inspectApplicableTarget,
   inspectApplicableUrl,
   inspectCriterionTarget,
   inspectCriterionUrl,
   listInteractionPatterns,
   listSupportedTargets,
   listWcagCriteria,
   listWcagLevels,
   resolveDefaultTarget,
   resolveDocumentTarget,
   resolveTargetType,
   runAxe,
   runDriverSessionAction,
   runEphemeralDriverAction,
   runInteractionPattern,
   searchWcagCriteria,
   showWcagCoverage,
   showWcagCriterion,
   startDriverSession,
   stopDriverSession,
   verifyCriterion,
   verifyLevel,
   CliEnvironmentError,
   CliUsageError,
} from '@a11ied/core';

export type {
   ResolveDocumentTargetInput,
   RunPatternOptions,
   SessionActionOptions,
   TargetType,
} from '@a11ied/core';
